### PR TITLE
All-in-one "installer" for a ZIO CLI application

### PR DESCRIPTION
**Pull request by Porcupine96**
This PR addresses #14

### CODE REVIEW

**Comment by jdegoes** [comment]
@Porcupine96 Awesome work here!

How extensively is this tested?

**Comment by Porcupine96** [comment]
We manually tried all the scenarios on Linux. Later today I'll try to run it on Mac as well.

**Comment by jdegoes** [comment]
@Porcupine96 Awesome. Let me know when your testing is done and we can get this merged!

**Comment by JakDar** [comment]
Just double checked all scenarios on Linux and found (and fixed) an issue with building native image.
Tests:
- just jar: https://asciinema.org/a/ig2V6OShbOOpISktckqasYer9
- using system graalvm: https://asciinema.org/a/9zphgk2QCVgx0guGTjMb6Sei5
- with downloading graalvm: https://asciinema.org/a/Df4bmy5PQa6i9k1z9AdvRdrzq

Of course subsequent reruns (after first run which installs app), just run application  without reinstalling ;)

@Porcupine96  , how is Mac holding up?

**Comment by Porcupine96** [comment]
I can confirm that it runs on my Mac that I haven't used for over a year 😃

**Comment by jdegoes** [comment]
Awesome, will merge as soon as we get a clean build!

**Comment by jdegoes** [comment]
@JakDar @Porcupine96 Merged, thank you both for your work on this!

**Pull request merged**
