### PR TITLE
Improve the help docs of commands

### PR DESCRIPTION
**Pull request by jorge-vasquez-2301**
This PR is to improve the help docs of commands. I've also taken the chance to do some code cleanup and refactoring.

### CODE REVIEW

**Comment by jorge-vasquez-2301** [comment]
This is how help docs look for a root command now:

image

**Comment by jorge-vasquez-2301** [comment]
This is how help docs look for a subcommand:

image

**Comment by jorge-vasquez-2301** [comment]
@kitlangton maybe you can take a look to this PR? 🙂

**Comment by jorge-vasquez-2301** [comment]
Or maybe @adamgfraser ?

**Review by jdegoes — APPROVED** [review]

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
