### PR TITLE
Closes #4 sbt plugin to build native image

### LINKED ISSUE #4: Create sbt-plugin to package CLI app as GraalVM native Docker image
A small and simple SBT plug-in that can package up a CLI application as a GraalVM native docker image would make it much easier to prepare ZIO CLI applications for deployment.

Perhaps [this](https://www.scala-sbt.org/sbt-native-packager/formats/graalvm-native-image.html#) could be a source of inspiration or a component of this solution.

### PR DESCRIPTION
**Pull request by alterationx10**
Still lots to clean up with this, but wanted to start a PR to get some feedback for improving.

I'm thinking it would be best to publish a separate artifact for the SBT plugin, that users could add to their project. I didn't have luck easily depending on is as a separate project, especially with it depending on a particular version of Scala. If that's the case, maybe (eventually) put it in it's own repo?

This mainly just calls from org.scalameta's sbt-native-image for the real work, and has a couple of settings that map 1:1 to that plugins settings. Would we want to do that, or rely on setting the "upstream" native image options?

### CODE REVIEW

**Comment by jdegoes** [comment]
@alterationx10 Thank you! Can you resolve the conflicts and also document the usage and state of this plug-in and additional work to do?

**Comment by alterationx10** [comment]
Absolutely! I'll try to get that in later today.

**Comment by jdegoes** [comment]
Awesome, thank you!

**Comment by alterationx10** [comment]
@jdegoes The conflict seems to have resolved itself 🎉  

I've done a little bit of naming/cleaning/refactoring, and added a `docs/overview/sbt_plugin.md` with some documentation + usage in it.

Please let me know if there's anything more to add to help make it clearer!

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@alterationx10 Awesome, thanks for your contribution!

**Pull request merged**
