### PR TITLE
Revert change in Command parsing logic

### PR DESCRIPTION
**Pull request by jorge-vasquez-2301**
Reverting a change I've made in Command parsing logic, because it was causing unwanted behaviour because of change in params order

### CODE REVIEW

**Comment by DamianReeves** [comment]
Is it possible to capture the issue you are trying to address in a test?

**Comment by jorge-vasquez-2301** [comment]
@DamianReeves done!

**Review by DamianReeves — APPROVED** [review]
LGTM

**Comment by DamianReeves** [comment]
> @DamianReeves done!

Thanks @jorge-vasquez-2301 - Approved

**Pull request merged**
